### ISSUE TITLE
Error creating post

### ISSUE THREAD

**Issue by efrapp** [Nazeh/members-only#2]
Team, please check this error:
<img width="562" alt="Screen Shot 2019-08-17 at 7 39 09 AM" src="https://user-images.githubusercontent.com/698811/63211839-424c5d00-c0c2-11e9-965e-1b45a58e07e9.png">

**Comment by Nazeh** [comment]
Hello @efrapp , thank you for your review.

Just updated the pull request so the creation of a post is only allowed while signed in, there is no signing up functionality though so please us:
```yml
email: User_0@example.com
password: "password"
```
 after running the command:
```console
rails db:seed
```
Thank you, please let me know if there are any more issues.
